dateModified: 1568143346
email:
  fromEmail: mathias@mathiasrenner.ch
  fromName: 'Mathias Renner'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  11fcf648-c46a-4cb9-bf9c-de04e8ce644a:
    name: Common
  623e8f21-c10a-45f4-a9bc-6329faaa52bd:
    name: 'Allgemeine Infos'
fields:
  6720cb60-b2a2-4056-aad9-2f33e3e8f6a5:
    name: Images
    handle: images
    instructions: 'Bilder für den Slider.'
    searchable: false
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: ''
      defaultUploadLocationSource: 'volume:50706d0d-adfc-4561-99a1-bad68c596824'
      defaultUploadLocationSubpath: ''
      singleUploadLocationSource: 'volume:50706d0d-adfc-4561-99a1-bad68c596824'
      singleUploadLocationSubpath: ''
      restrictFiles: '1'
      allowedKinds:
        - image
      sources:
        - 'volume:50706d0d-adfc-4561-99a1-bad68c596824'
      source: null
      targetSiteId: null
      viewMode: list
      limit: ''
      selectionLabel: 'Bild wählen'
      localizeRelations: false
    contentColumnType: string
    fieldGroup: 11fcf648-c46a-4cb9-bf9c-de04e8ce644a
  21293d2c-4fb2-495e-aa59-0fa17b99be9b:
    name: 'E-Mail Adresse'
    handle: mail
    instructions: ''
    searchable: false
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\Email
    settings:
      placeholder: ''
    contentColumnType: string
    fieldGroup: 623e8f21-c10a-45f4-a9bc-6329faaa52bd
  d4150027-0159-4468-aead-b1b4c07d760e:
    name: Telefon-Nummer
    handle: phone
    instructions: ''
    searchable: false
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 623e8f21-c10a-45f4-a9bc-6329faaa52bd
  3dc7f4b8-8afa-486d-a5ff-363b1b8816ed:
    name: Claim
    handle: claim
    instructions: ''
    searchable: false
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 623e8f21-c10a-45f4-a9bc-6329faaa52bd
  b31016bc-7398-4a61-a43f-3689e5dc9803:
    name: 'Hochformat (Einzelbild)'
    handle: singleHigh
    instructions: 'Wird auf grösseren Bildschirmen gleich gross angezeigt, wie doppelte Hochformate.'
    searchable: false
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\Lightswitch
    settings:
      default: ''
    contentColumnType: boolean
    fieldGroup: 11fcf648-c46a-4cb9-bf9c-de04e8ce644a
globalSets:
  c8bf5d7f-1f31-4bb7-9d04-78c316ce9c10:
    name: 'Allgemeine Infos'
    handle: infos
    fieldLayouts:
      994314ce-1e73-4e7d-99cc-3165b6d64f1f:
        tabs:
          -
            name: 'Allgemeine Infos'
            sortOrder: 1
            fields:
              3dc7f4b8-8afa-486d-a5ff-363b1b8816ed:
                required: false
                sortOrder: 1
              d4150027-0159-4468-aead-b1b4c07d760e:
                required: false
                sortOrder: 2
              21293d2c-4fb2-495e-aa59-0fa17b99be9b:
                required: false
                sortOrder: 3
sections:
  bce5974d-8954-41f8-b59b-205ef241305b:
    name: Home
    handle: home
    type: single
    enableVersioning: true
    propagateEntries: true
    siteSettings:
      48c3aa5b-eec3-4454-a328-a3e1a4f647c2:
        enabledByDefault: true
        hasUrls: true
        uriFormat: /
        template: index
    entryTypes:
      a1bce3f6-26c4-41e3-a964-61f59c4628f1:
        name: Home
        handle: home
        hasTitleField: false
        titleLabel: 'Mathias renner'
        titleFormat: '{section.name|raw}'
        sortOrder: 1
  89b09de4-f600-43e5-a40c-2c1273849092:
    name: Projekte
    handle: projects
    type: structure
    enableVersioning: true
    propagateEntries: true
    siteSettings:
      48c3aa5b-eec3-4454-a328-a3e1a4f647c2:
        enabledByDefault: true
        hasUrls: true
        uriFormat: 'projects/{slug}'
        template: ''
    structure:
      uid: 3e672880-8754-4593-b2a7-35aa673eb366
      maxLevels: '1'
    entryTypes:
      c5144144-9639-47fb-b07e-eb1096795e90:
        name: Projekt
        handle: project
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          8fb6421c-2521-46d2-ad79-ae22733ca6e4:
            tabs:
              -
                name: Common
                sortOrder: 1
                fields:
                  6720cb60-b2a2-4056-aad9-2f33e3e8f6a5:
                    required: false
                    sortOrder: 1
                  b31016bc-7398-4a61-a43f-3689e5dc9803:
                    required: false
                    sortOrder: 2
siteGroups:
  dbd97a29-b0b8-4f99-b883-5bbceef9034b:
    name: 'Mathias Renner'
sites:
  48c3aa5b-eec3-4454-a328-a3e1a4f647c2:
    siteGroup: dbd97a29-b0b8-4f99-b883-5bbceef9034b
    name: 'Mathias Renner'
    handle: default
    language: en-US
    hasUrls: true
    baseUrl: '@web'
    sortOrder: 1
    primary: true
system:
  edition: solo
  name: 'Mathias Renner'
  live: true
  schemaVersion: 3.1.25
  timeZone: Europe/Zurich
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
volumes:
  50706d0d-adfc-4561-99a1-bad68c596824:
    name: Uploads
    handle: uploads
    type: craft\volumes\Local
    hasUrls: true
    url: /assets/uploads/
    settings:
      path: '@webroot/assets/uploads'
    sortOrder: '2'
