dateModified: 1576102056
email:
  fromEmail: mathias@mathiasrenner.ch
  fromName: 'Mathias Renner'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  11fcf648-c46a-4cb9-bf9c-de04e8ce644a:
    name: Common
  623e8f21-c10a-45f4-a9bc-6329faaa52bd:
    name: 'Allgemeine Infos'
fields:
  6720cb60-b2a2-4056-aad9-2f33e3e8f6a5:
    name: Bilder
    handle: images
    instructions: ''
    searchable: false
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: ''
      defaultUploadLocationSource: 'volume:50706d0d-adfc-4561-99a1-bad68c596824'
      defaultUploadLocationSubpath: ''
      singleUploadLocationSource: 'volume:50706d0d-adfc-4561-99a1-bad68c596824'
      singleUploadLocationSubpath: ''
      restrictFiles: '1'
      allowedKinds:
        - image
      sources:
        - 'volume:50706d0d-adfc-4561-99a1-bad68c596824'
      source: null
      targetSiteId: null
      viewMode: list
      limit: ''
      selectionLabel: 'Bild wählen'
      localizeRelations: false
    contentColumnType: string
    fieldGroup: 11fcf648-c46a-4cb9-bf9c-de04e8ce644a
  21293d2c-4fb2-495e-aa59-0fa17b99be9b:
    name: 'E-Mail Adresse'
    handle: mail
    instructions: ''
    searchable: false
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\Email
    settings:
      placeholder: ''
    contentColumnType: string
    fieldGroup: 623e8f21-c10a-45f4-a9bc-6329faaa52bd
  d4150027-0159-4468-aead-b1b4c07d760e:
    name: Telefon-Nummer
    handle: phone
    instructions: ''
    searchable: false
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 623e8f21-c10a-45f4-a9bc-6329faaa52bd
  3dc7f4b8-8afa-486d-a5ff-363b1b8816ed:
    name: Claim
    handle: claim
    instructions: ''
    searchable: false
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 623e8f21-c10a-45f4-a9bc-6329faaa52bd
  b31016bc-7398-4a61-a43f-3689e5dc9803:
    name: Hochformat
    handle: singleHigh
    instructions: 'Hat nur bei Einzelbild einen Effekt. Einzelbild wird auf grösseren Bildschirmen gleich gross angezeigt wie doppelte Hochformate.'
    searchable: false
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\Lightswitch
    settings:
      default: ''
    contentColumnType: boolean
    fieldGroup: 11fcf648-c46a-4cb9-bf9c-de04e8ce644a
  d1007392-cdf0-4bfe-890d-0e31f5092101:
    name: 'Portfolio Upload'
    handle: portfolio
    instructions: 'PDF Upload'
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: '1'
      defaultUploadLocationSource: 'volume:50706d0d-adfc-4561-99a1-bad68c596824'
      defaultUploadLocationSubpath: ''
      singleUploadLocationSource: 'volume:50706d0d-adfc-4561-99a1-bad68c596824'
      singleUploadLocationSubpath: portfolio
      restrictFiles: '1'
      allowedKinds:
        - pdf
      sources: '*'
      source: null
      targetSiteId: null
      viewMode: list
      limit: '1'
      selectionLabel: 'Add Portfolio'
      localizeRelations: false
    contentColumnType: string
    fieldGroup: 11fcf648-c46a-4cb9-bf9c-de04e8ce644a
  d6b4bc2e-e70a-4df1-aab3-764a176f112d:
    name: 'Suchmaschinen Text'
    handle: SEO_snippet
    instructions: 'Wird von Suchmaschinen erfasst und mit Suchresultat angezeigt.'
    searchable: false
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: 623e8f21-c10a-45f4-a9bc-6329faaa52bd
globalSets:
  c8bf5d7f-1f31-4bb7-9d04-78c316ce9c10:
    name: 'Allgemeine Infos'
    handle: infos
    fieldLayouts:
      994314ce-1e73-4e7d-99cc-3165b6d64f1f:
        tabs:
          -
            name: 'Allgemeine Infos'
            sortOrder: 1
            fields:
              3dc7f4b8-8afa-486d-a5ff-363b1b8816ed:
                required: false
                sortOrder: 1
              d4150027-0159-4468-aead-b1b4c07d760e:
                required: false
                sortOrder: 2
              21293d2c-4fb2-495e-aa59-0fa17b99be9b:
                required: false
                sortOrder: 3
              d6b4bc2e-e70a-4df1-aab3-764a176f112d:
                required: false
                sortOrder: 4
plugins:
  sitemap:
    edition: standard
    enabled: true
    schemaVersion: 1.0.2
sections:
  bce5974d-8954-41f8-b59b-205ef241305b:
    name: Home
    handle: home
    type: single
    enableVersioning: true
    propagateEntries: true
    siteSettings:
      48c3aa5b-eec3-4454-a328-a3e1a4f647c2:
        enabledByDefault: true
        hasUrls: true
        uriFormat: /
        template: index
    entryTypes:
      a1bce3f6-26c4-41e3-a964-61f59c4628f1:
        name: Home
        handle: home
        hasTitleField: false
        titleLabel: 'Mathias renner'
        titleFormat: '{section.name|raw}'
        sortOrder: 1
  89b09de4-f600-43e5-a40c-2c1273849092:
    name: Projekte
    handle: projects
    type: structure
    enableVersioning: true
    propagateEntries: true
    siteSettings:
      48c3aa5b-eec3-4454-a328-a3e1a4f647c2:
        enabledByDefault: true
        hasUrls: false
        uriFormat: null
        template: null
    structure:
      uid: 3e672880-8754-4593-b2a7-35aa673eb366
      maxLevels: '1'
    entryTypes:
      c5144144-9639-47fb-b07e-eb1096795e90:
        name: Projekt
        handle: project
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          8fb6421c-2521-46d2-ad79-ae22733ca6e4:
            tabs:
              -
                name: 🐈
                sortOrder: 1
                fields:
                  6720cb60-b2a2-4056-aad9-2f33e3e8f6a5:
                    required: false
                    sortOrder: 1
                  b31016bc-7398-4a61-a43f-3689e5dc9803:
                    required: false
                    sortOrder: 2
  b4b573d4-09e5-4cef-b829-29055e286a8c:
    name: Portfolio
    handle: portfolio
    type: single
    enableVersioning: true
    propagateEntries: true
    siteSettings:
      48c3aa5b-eec3-4454-a328-a3e1a4f647c2:
        enabledByDefault: true
        hasUrls: true
        uriFormat: portfolio
        template: portfolio
    entryTypes:
      8c5e78b0-038a-4674-a98f-dec60fb0df41:
        name: Portfolio
        handle: portfolio
        hasTitleField: false
        titleLabel: ''
        titleFormat: '{section.name|raw}'
        sortOrder: 1
        fieldLayouts:
          692eb8eb-dc66-45a4-b7c9-f986121d230a:
            tabs:
              -
                name: 🐉
                sortOrder: 1
                fields:
                  d1007392-cdf0-4bfe-890d-0e31f5092101:
                    required: false
                    sortOrder: 1
  a35494af-907c-4e0a-82fa-b0ac5bccc08f:
    name: work
    handle: work
    type: single
    enableVersioning: true
    propagateEntries: true
    siteSettings:
      48c3aa5b-eec3-4454-a328-a3e1a4f647c2:
        enabledByDefault: true
        hasUrls: true
        uriFormat: work
        template: work
    entryTypes:
      4cc28026-d4b1-4841-8ea9-748b4982ec6c:
        name: work
        handle: work
        hasTitleField: false
        titleLabel: null
        titleFormat: '{section.name|raw}'
        sortOrder: 1
  b394bdc2-9088-4fe3-8fc8-1bd3857cb309:
    name: archive
    handle: archive
    type: single
    enableVersioning: true
    propagateEntries: true
    siteSettings:
      48c3aa5b-eec3-4454-a328-a3e1a4f647c2:
        enabledByDefault: true
        hasUrls: true
        uriFormat: archive
        template: archive
    entryTypes:
      454db89b-e06f-49aa-877e-0df47209903b:
        name: archive
        handle: archive
        hasTitleField: false
        titleLabel: null
        titleFormat: '{section.name|raw}'
        sortOrder: 1
  f902edad-95e7-4e49-bd68-8989a0831fb7:
    name: 'Work Projects'
    handle: workProjects
    type: structure
    enableVersioning: true
    propagateEntries: true
    siteSettings:
      48c3aa5b-eec3-4454-a328-a3e1a4f647c2:
        enabledByDefault: true
        hasUrls: false
        uriFormat: null
        template: null
    structure:
      uid: 0e1c5aa7-5b88-4d5e-a6b4-497412eae906
      maxLevels: '1'
    entryTypes:
      92c3dd64-d7c8-443c-839d-45c98b8d5777:
        name: 'Work Projekt'
        handle: workProject
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          339f82fe-dbe6-4b8c-b515-662856de2934:
            tabs:
              -
                name: 'Tab 1'
                sortOrder: 1
                fields:
                  6720cb60-b2a2-4056-aad9-2f33e3e8f6a5:
                    required: false
                    sortOrder: 1
                  b31016bc-7398-4a61-a43f-3689e5dc9803:
                    required: false
                    sortOrder: 2
  8b81fe86-f7ad-482c-baee-7ca4e9114e5a:
    name: 'Archive Projects'
    handle: archiveProjects
    type: structure
    enableVersioning: true
    propagateEntries: true
    siteSettings:
      48c3aa5b-eec3-4454-a328-a3e1a4f647c2:
        enabledByDefault: true
        hasUrls: false
        uriFormat: null
        template: null
    structure:
      uid: 81e2e04f-2a49-4b20-86ee-459b7cfef917
      maxLevels: '1'
    entryTypes:
      ab6d0c4e-f9b3-41d2-86be-35f066c0229c:
        name: 'Archiv Projekt'
        handle: archiveProject
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          8c5f50e6-c54e-495f-a4dc-2e21e247403d:
            tabs:
              -
                name: 'Tab 1'
                sortOrder: 1
                fields:
                  6720cb60-b2a2-4056-aad9-2f33e3e8f6a5:
                    required: false
                    sortOrder: 1
                  b31016bc-7398-4a61-a43f-3689e5dc9803:
                    required: false
                    sortOrder: 2
siteGroups:
  dbd97a29-b0b8-4f99-b883-5bbceef9034b:
    name: 'Mathias Renner'
sites:
  48c3aa5b-eec3-4454-a328-a3e1a4f647c2:
    siteGroup: dbd97a29-b0b8-4f99-b883-5bbceef9034b
    name: 'Mathias Renner'
    handle: default
    language: en-US
    hasUrls: true
    baseUrl: '@web'
    sortOrder: 1
    primary: true
system:
  edition: solo
  name: 'Mathias Renner'
  live: true
  schemaVersion: 3.1.25
  timeZone: Europe/Zurich
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
volumes:
  50706d0d-adfc-4561-99a1-bad68c596824:
    name: Uploads
    handle: uploads
    type: craft\volumes\Local
    hasUrls: true
    url: /assets/uploads/
    settings:
      path: '@webroot/assets/uploads'
    sortOrder: '2'
